export const headerMenu: Props.HeaderMenu[] = [
  {
    idx: 0,
    text: "All",
    path: "/product/all",
  },
  {
    idx: 1,
    text: "Outer",
    path: "/product/outer",
  },
  {
    idx: 2,
    text: "Top",
    path: "/product/top",
  },
  {
    idx: 3,
    text: "Bottom",
    path: "/product/bottom",
  },
  {
    idx: 4,
    text: "Accessories",
    path: "/product/accessories",
  },
];

export const userMenu: Props.HeaderMenu[] = [
  {
    idx: 0,
    text: "Contact",
    path: "/contact",
  },
  {
    idx: 1,
    text: "Login",
    path: "/login",
  },
  {
    idx: 2,
    text: "Cart",
    path: "/order/cart",
  },
];

export const clothes: Props.ClothInfo[] = [
  {
    name: "SHORT T-SHIRT BLACK",
    category: "top",
    price: "KRW 29,000",
    default_img: "/top/t_shirt_black_f.png",
    mouse_over_img: "/top/t_shirt_black_b.png",
  },
  {
    name: "SHORT T-SHIRT WHITE",
    category: "top",
    price: "KRW 29,000",
    default_img: "/top/t_shirt_white_f.png",
    mouse_over_img: "/top/t_shirt_white_b.png",
  },
  {
    name: "SHORT T-SHIRT RED",
    category: "top",
    price: "KRW 29,000",
    default_img: "/top/t_shirt_red_f.png",
    mouse_over_img: "/top/t_shirt_red_b.png",
  },
  {
    name: "SHORT T-SHIRT CHARCOAL",
    category: "top",
    price: "KRW 29,000",
    default_img: "/top/t_shirt_charcoal_f.png",
    mouse_over_img: "/top/t_shirt_charcoal_b.png",
  },
  {
    name: "POCKET T-SHIRT BLACK",
    category: "top",
    price: "KRW 39,000",
    default_img: "/top/pocket_t_shirt_black_f.png",
    mouse_over_img: "/top/pocket_t_shirt_black_b.png",
  },
  {
    name: "POCKET T-SHIRT WHITE",
    category: "top",
    price: "KRW 39,000",
    default_img: "/top/pocket_t_shirt_white_f.png",
    mouse_over_img: "/top/pocket_t_shirt_white_b.png",
  },
  {
    name: "POCKET T-SHIRT RED",
    category: "top",
    price: "KRW 39,000",
    default_img: "/top/pocket_t_shirt_red_f.png",
    mouse_over_img: "/top/pocket_t_shirt_red_b.png",
  },
  {
    name: "POCKET T-SHIRT CHARCOAL",
    category: "top",
    price: "KRW 39,000",
    default_img: "/top/pocket_t_shirt_charcoal_f.png",
    mouse_over_img: "/top/pocket_t_shirt_charcoal_b.png",
  },
  {
    name: "TWO BUTTON JACKET BLACK",
    category: "outer",
    price: "KRW 79,000",
    default_img: "/outer/two_button_jacket_black_f.png",
    mouse_over_img: "/outer/two_button_jacket_black_b.png",
  },
  {
    name: "TWO BUTTON JACKET CHARCOAL",
    category: "outer",
    price: "KRW 79,000",
    default_img: "/outer/two_button_jacket_charcoal_f.png",
    mouse_over_img: "/outer/two_button_jacket_charcoal_b.png",
  },
  {
    name: "SHORT SLEEVE SHIRT PINK",
    category: "outer",
    price: "KRW 59,000",
    default_img: "/outer/short_sleeve_shirt_pink_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_pink_b.png",
  },
  {
    name: "SHORT SLEEVE SHIRT BROWN",
    category: "outer",
    price: "KRW 59,000",
    default_img: "/outer/short_sleeve_shirt_brown_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_brown_b.png",
  },
  {
    name: "SHORT SLEEVE SHIRT LIGHT PURPLE",
    category: "outer",
    price: "KRW 59,000",
    default_img: "/outer/short_sleeve_shirt_light_purple_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_light_purple_b.png",
  },
  {
    name: "SHORT SLEEVE SHIRT SKY BLUE",
    category: "outer",
    price: "KRW 59,000",
    default_img: "/outer/short_sleeve_shirt_sky_blue_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_sky_blue_b.png",
  },
  {
    name: "REGULAR PANTS BLACK",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_black_f.png",
    mouse_over_img: "/bottom/regular_pants_black_b.png",
  },
  {
    name: "REGULAR PANTS CHARCOAL",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_charcoal_f.png",
    mouse_over_img: "/bottom/regular_pants_charcoal_b.png",
  },
  {
    name: "REGULAR PANTS KHAKI",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_khaki_f.png",
    mouse_over_img: "/bottom/regular_pants_khaki_b.png",
  },
  {
    name: "REGULAR PANTS DARK BLUE",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_dark_blue_f.png",
    mouse_over_img: "/bottom/regular_pants_dark_blue_b.png",
  },
  {
    name: "REGULAR PANTS MIDDLE BLUE",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_middle_blue_f.png",
    mouse_over_img: "/bottom/regular_pants_middle_blue_b.png",
  },
  {
    name: "REGULAR PANTS LIGHT BLUE",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_light_blue_f.png",
    mouse_over_img: "/bottom/regular_pants_light_blue_b.png",
  },
  {
    name: "REGULAR PANTS PINK",
    category: "bottom",
    price: "KRW 49,000",
    default_img: "/bottom/regular_pants_pink_f.png",
    mouse_over_img: "/bottom/regular_pants_pink_b.png",
  },
  {
    name: "SHOUDLER BAG BLACK",
    category: "accessories",
    price: "KRW 59,000",
    default_img: "/acc/bag_black_f.png",
    mouse_over_img: "/acc/bag_black_b.png",
  },
  {
    name: "SHOUDLER BAG SILVER",
    category: "accessories",
    price: "KRW 59,000",
    default_img: "/acc/bag_silver_f.png",
    mouse_over_img: "/acc/bag_silver_b.png",
  },
  {
    name: "SHOUDLER BAG GREEN",
    category: "accessories",
    price: "KRW 79,000",
    default_img: "/acc/shoulder_bag_green_f.png",
    mouse_over_img: "/acc/shoulder_bag_green_b.png",
  },
  {
    name: "SHOUDLER BAG SILVER",
    category: "accessories",
    price: "KRW 79,000",
    default_img: "/acc/shoulder_bag_silver_f.png",
    mouse_over_img: "/acc/shoulder_bag_silver_b.png",
  },
];