export const headerMenu: Props.HeaderMenu[] = [
  {
    idx: 0,
    text: "All",
    path: "/product/all",
  },
  {
    idx: 1,
    text: "Outer",
    path: "/product/outer",
  },
  {
    idx: 2,
    text: "Top",
    path: "/product/top",
  },
  {
    idx: 3,
    text: "Bottom",
    path: "/product/bottom",
  },
  {
    idx: 4,
    text: "Accessories",
    path: "/product/acc",
  },
];

export const userMenu: Props.HeaderMenu[] = [
  {
    idx: 0,
    text: "Contact",
    path: "/contact",
  },
  {
    idx: 1,
    text: "Login",
    path: "/login",
  },
  {
    idx: 2,
    text: "MyPage",
    path: "/mypage",
  },
  {
    idx: 3,
    text: "Cart",
    path: "/order/cart",
  },
];

export const clothes: Props.ClothInfo[] = [
  {
    idx: 0,
    name: "SHORT T-SHIRT BLACK",
    category: "top",
    price: 29000,
    default_img: "/top/t_shirt_black_f.png",
    mouse_over_img: "/top/t_shirt_black_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 1,
    name: "SHORT T-SHIRT WHITE",
    category: "top",
    price: 29000,
    default_img: "/top/t_shirt_white_f.png",
    mouse_over_img: "/top/t_shirt_white_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 2,
    name: "SHORT T-SHIRT RED",
    category: "top",
    price: 29000,
    default_img: "/top/t_shirt_red_f.png",
    mouse_over_img: "/top/t_shirt_red_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 3,
    name: "SHORT T-SHIRT CHARCOAL",
    category: "top",
    price: 29000,
    default_img: "/top/t_shirt_charcoal_f.png",
    mouse_over_img: "/top/t_shirt_charcoal_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 4,
    name: "POCKET T-SHIRT BLACK",
    category: "top",
    price: 39000,
    default_img: "/top/pocket_t_shirt_black_f.png",
    mouse_over_img: "/top/pocket_t_shirt_black_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 5,
    name: "POCKET T-SHIRT WHITE",
    category: "top",
    price: 39000,
    default_img: "/top/pocket_t_shirt_white_f.png",
    mouse_over_img: "/top/pocket_t_shirt_white_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 6,
    name: "POCKET T-SHIRT RED",
    category: "top",
    price: 39000,
    default_img: "/top/pocket_t_shirt_red_f.png",
    mouse_over_img: "/top/pocket_t_shirt_red_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 7,
    name: "POCKET T-SHIRT CHARCOAL",
    category: "top",
    price: 39000,
    default_img: "/top/pocket_t_shirt_charcoal_f.png",
    mouse_over_img: "/top/pocket_t_shirt_charcoal_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 8,
    name: "TWO BUTTON JACKET BLACK",
    category: "outer",
    price: 79000,
    default_img: "/outer/two_button_jacket_black_f.png",
    mouse_over_img: "/outer/two_button_jacket_black_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 9,
    name: "TWO BUTTON JACKET CHARCOAL",
    category: "outer",
    price: 79000,
    default_img: "/outer/two_button_jacket_charcoal_f.png",
    mouse_over_img: "/outer/two_button_jacket_charcoal_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 10,
    name: "SHORT SLEEVE SHIRT PINK",
    category: "outer",
    price: 59000,
    default_img: "/outer/short_sleeve_shirt_pink_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_pink_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 11,
    name: "SHORT SLEEVE SHIRT BROWN",
    category: "outer",
    price: 59000,
    default_img: "/outer/short_sleeve_shirt_brown_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_brown_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 12,
    name: "SHORT SLEEVE SHIRT LIGHT PURPLE",
    category: "outer",
    price: 59000,
    default_img: "/outer/short_sleeve_shirt_light_purple_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_light_purple_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 13,
    name: "SHORT SLEEVE SHIRT SKY BLUE",
    category: "outer",
    price: 59000,
    default_img: "/outer/short_sleeve_shirt_sky_blue_f.png",
    mouse_over_img: "/outer/short_sleeve_shirt_sky_blue_b.png",
    option: ["S", "M", "L", "XL", "2XL"],
  },
  {
    idx: 14,
    name: "REGULAR PANTS BLACK",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_black_f.png",
    mouse_over_img: "/bottom/regular_pants_black_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 15,
    name: "REGULAR PANTS CHARCOAL",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_charcoal_f.png",
    mouse_over_img: "/bottom/regular_pants_charcoal_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 16,
    name: "REGULAR PANTS KHAKI",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_khaki_f.png",
    mouse_over_img: "/bottom/regular_pants_khaki_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 17,
    name: "REGULAR PANTS DARK BLUE",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_dark_blue_f.png",
    mouse_over_img: "/bottom/regular_pants_dark_blue_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 18,
    name: "REGULAR PANTS MIDDLE BLUE",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_middle_blue_f.png",
    mouse_over_img: "/bottom/regular_pants_middle_blue_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 19,
    name: "REGULAR PANTS LIGHT BLUE",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_light_blue_f.png",
    mouse_over_img: "/bottom/regular_pants_light_blue_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 20,
    name: "REGULAR PANTS PINK",
    category: "bottom",
    price: 49000,
    default_img: "/bottom/regular_pants_pink_f.png",
    mouse_over_img: "/bottom/regular_pants_pink_b.png",
    option: ["28", "30", "32", "34", "36"],
  },
  {
    idx: 21,
    name: "SHOUDLER BAG BLACK",
    category: "acc",
    price: 59000,
    default_img: "/acc/bag_black_f.png",
    mouse_over_img: "/acc/bag_black_b.png",
    option: ["OS"],
  },
  {
    idx: 22,
    name: "SHOUDLER BAG SILVER",
    category: "acc",
    price: 59000,
    default_img: "/acc/bag_silver_f.png",
    mouse_over_img: "/acc/bag_silver_b.png",
    option: ["OS"],
  },
  {
    idx: 23,
    name: "SHOUDLER BAG GREEN",
    category: "acc",
    price: 79000,
    default_img: "/acc/shoulder_bag_green_f.png",
    mouse_over_img: "/acc/shoulder_bag_green_b.png",
    option: ["OS"],
  },
  {
    idx: 24,
    name: "SHOUDLER BAG SILVER",
    category: "acc",
    price: 79000,
    default_img: "/acc/shoulder_bag_silver_f.png",
    mouse_over_img: "/acc/shoulder_bag_silver_b.png",
    option: ["OS"],
  },
];